### ISSUE TITLE
Para la tarea

### ISSUE THREAD

**Issue by MorosiniP** [pdepjm/2023-tp0-presentacion-NoahSantander#1]
Como esta paradonaa , emana buen futbol y elegancia (?
Como hizo el click de un momento al otro ojala se consagre como le paso al pity

**Comment by NoahSantander** [comment]
Totalmente. Para mi esta durmiendo Scaloni al no convocarlo

**Comment by MorosiniP** [comment]
La verdad que  si! Que renuncie scaloni ya, sin paradela no hay fulbo 🚬
